// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: vehicle.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReqByNoLambung struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nolambung string `protobuf:"bytes,1,opt,name=nolambung,proto3" json:"nolambung,omitempty"`
}

func (x *ReqByNoLambung) Reset() {
	*x = ReqByNoLambung{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqByNoLambung) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByNoLambung) ProtoMessage() {}

func (x *ReqByNoLambung) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByNoLambung.ProtoReflect.Descriptor instead.
func (*ReqByNoLambung) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *ReqByNoLambung) GetNolambung() string {
	if x != nil {
		return x.Nolambung
	}
	return ""
}

type ReqAllByPrsh struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kodeperusahaan string `protobuf:"bytes,1,opt,name=kodeperusahaan,proto3" json:"kodeperusahaan,omitempty"`
}

func (x *ReqAllByPrsh) Reset() {
	*x = ReqAllByPrsh{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAllByPrsh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAllByPrsh) ProtoMessage() {}

func (x *ReqAllByPrsh) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAllByPrsh.ProtoReflect.Descriptor instead.
func (*ReqAllByPrsh) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *ReqAllByPrsh) GetKodeperusahaan() string {
	if x != nil {
		return x.Kodeperusahaan
	}
	return ""
}

type ReqByPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kodepool string `protobuf:"bytes,1,opt,name=kodepool,proto3" json:"kodepool,omitempty"`
}

func (x *ReqByPool) Reset() {
	*x = ReqByPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqByPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqByPool) ProtoMessage() {}

func (x *ReqByPool) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqByPool.ProtoReflect.Descriptor instead.
func (*ReqByPool) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *ReqByPool) GetKodepool() string {
	if x != nil {
		return x.Kodepool
	}
	return ""
}

type ResVehicleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleList []*VehicleModel `protobuf:"bytes,1,rep,name=vehicleList,proto3" json:"vehicleList,omitempty"`
}

func (x *ResVehicleList) Reset() {
	*x = ResVehicleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResVehicleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResVehicleList) ProtoMessage() {}

func (x *ResVehicleList) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResVehicleList.ProtoReflect.Descriptor instead.
func (*ResVehicleList) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *ResVehicleList) GetVehicleList() []*VehicleModel {
	if x != nil {
		return x.VehicleList
	}
	return nil
}

type VehicleModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kodepool       string `protobuf:"bytes,1,opt,name=kodepool,proto3" json:"kodepool,omitempty"`
	Nolambung      string `protobuf:"bytes,2,opt,name=nolambung,proto3" json:"nolambung,omitempty"`
	Nopolisi       string `protobuf:"bytes,3,opt,name=nopolisi,proto3" json:"nopolisi,omitempty"`
	Jenisservice   string `protobuf:"bytes,4,opt,name=jenisservice,proto3" json:"jenisservice,omitempty"`
	Kodeperusahaan string `protobuf:"bytes,5,opt,name=kodeperusahaan,proto3" json:"kodeperusahaan,omitempty"`
	Kodebmb1       string `protobuf:"bytes,6,opt,name=kodebmb1,proto3" json:"kodebmb1,omitempty"`
	Kodebmm2       string `protobuf:"bytes,7,opt,name=kodebmm2,proto3" json:"kodebmm2,omitempty"`
	Kodeargo       string `protobuf:"bytes,8,opt,name=kodeargo,proto3" json:"kodeargo,omitempty"`
	Issticker      bool   `protobuf:"varint,9,opt,name=issticker,proto3" json:"issticker,omitempty"`
	IsDeleted      bool   `protobuf:"varint,10,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
}

func (x *VehicleModel) Reset() {
	*x = VehicleModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleModel) ProtoMessage() {}

func (x *VehicleModel) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleModel.ProtoReflect.Descriptor instead.
func (*VehicleModel) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *VehicleModel) GetKodepool() string {
	if x != nil {
		return x.Kodepool
	}
	return ""
}

func (x *VehicleModel) GetNolambung() string {
	if x != nil {
		return x.Nolambung
	}
	return ""
}

func (x *VehicleModel) GetNopolisi() string {
	if x != nil {
		return x.Nopolisi
	}
	return ""
}

func (x *VehicleModel) GetJenisservice() string {
	if x != nil {
		return x.Jenisservice
	}
	return ""
}

func (x *VehicleModel) GetKodeperusahaan() string {
	if x != nil {
		return x.Kodeperusahaan
	}
	return ""
}

func (x *VehicleModel) GetKodebmb1() string {
	if x != nil {
		return x.Kodebmb1
	}
	return ""
}

func (x *VehicleModel) GetKodebmm2() string {
	if x != nil {
		return x.Kodebmm2
	}
	return ""
}

func (x *VehicleModel) GetKodeargo() string {
	if x != nil {
		return x.Kodeargo
	}
	return ""
}

func (x *VehicleModel) GetIssticker() bool {
	if x != nil {
		return x.Issticker
	}
	return false
}

func (x *VehicleModel) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ResEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResEmpty) Reset() {
	*x = ResEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResEmpty) ProtoMessage() {}

func (x *ResEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResEmpty.ProtoReflect.Descriptor instead.
func (*ResEmpty) Descriptor() ([]byte, []int) {
	return file_vehicle_proto_rawDescGZIP(), []int{5}
}

var File_vehicle_proto protoreflect.FileDescriptor

var file_vehicle_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x42, 0x79, 0x4e,
	0x6f, 0x4c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x6c, 0x61,
	0x6d, 0x62, 0x75, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x6c,
	0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x22, 0x36, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x41, 0x6c, 0x6c,
	0x42, 0x79, 0x50, 0x72, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x6b, 0x6f, 0x64, 0x65, 0x70, 0x65,
	0x72, 0x75, 0x73, 0x61, 0x68, 0x61, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x6b, 0x6f, 0x64, 0x65, 0x70, 0x65, 0x72, 0x75, 0x73, 0x61, 0x68, 0x61, 0x61, 0x6e, 0x22, 0x27,
	0x0a, 0x09, 0x52, 0x65, 0x71, 0x42, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x6f, 0x64, 0x65, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x6f, 0x64, 0x65, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x47, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0xc0, 0x02, 0x0a, 0x0c, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x6f, 0x6c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x6f, 0x6c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x6f, 0x70, 0x6f, 0x6c, 0x69, 0x73, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x70, 0x6f, 0x6c, 0x69, 0x73, 0x69, 0x12, 0x22, 0x0a, 0x0c, 0x6a, 0x65, 0x6e, 0x69, 0x73,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6a,
	0x65, 0x6e, 0x69, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6b,
	0x6f, 0x64, 0x65, 0x70, 0x65, 0x72, 0x75, 0x73, 0x61, 0x68, 0x61, 0x61, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x6b, 0x6f, 0x64, 0x65, 0x70, 0x65, 0x72, 0x75, 0x73, 0x61, 0x68,
	0x61, 0x61, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x62, 0x6d, 0x62, 0x31, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x62, 0x6d, 0x62, 0x31, 0x12,
	0x1a, 0x0a, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x62, 0x6d, 0x6d, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6b, 0x6f, 0x64, 0x65, 0x62, 0x6d, 0x6d, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x6f, 0x64, 0x65, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b,
	0x6f, 0x64, 0x65, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0xd2, 0x02, 0x0a, 0x07, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x04, 0x45, 0x64,
	0x69, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x42, 0x79, 0x4e, 0x6f, 0x4c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x1a, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x6f, 0x4c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67,
	0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x42, 0x79, 0x4e, 0x6f,
	0x4c, 0x61, 0x6d, 0x62, 0x75, 0x6e, 0x67, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x42, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x1a, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x79, 0x50, 0x72, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x71, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x50, 0x72, 0x73, 0x68, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_proto_rawDescData = file_vehicle_proto_rawDesc
)

func file_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(file_vehicle_proto_rawDescData)
	})
	return file_vehicle_proto_rawDescData
}

var file_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vehicle_proto_goTypes = []interface{}{
	(*ReqByNoLambung)(nil), // 0: proto.ReqByNoLambung
	(*ReqAllByPrsh)(nil),   // 1: proto.ReqAllByPrsh
	(*ReqByPool)(nil),      // 2: proto.ReqByPool
	(*ResVehicleList)(nil), // 3: proto.ResVehicleList
	(*VehicleModel)(nil),   // 4: proto.VehicleModel
	(*ResEmpty)(nil),       // 5: proto.ResEmpty
}
var file_vehicle_proto_depIdxs = []int32{
	4, // 0: proto.ResVehicleList.vehicleList:type_name -> proto.VehicleModel
	4, // 1: proto.Vehicle.Add:input_type -> proto.VehicleModel
	4, // 2: proto.Vehicle.Edit:input_type -> proto.VehicleModel
	0, // 3: proto.Vehicle.Delete:input_type -> proto.ReqByNoLambung
	0, // 4: proto.Vehicle.GetByNoLambung:input_type -> proto.ReqByNoLambung
	2, // 5: proto.Vehicle.GetByPool:input_type -> proto.ReqByPool
	1, // 6: proto.Vehicle.GetAllByPrsh:input_type -> proto.ReqAllByPrsh
	5, // 7: proto.Vehicle.Add:output_type -> proto.ResEmpty
	5, // 8: proto.Vehicle.Edit:output_type -> proto.ResEmpty
	5, // 9: proto.Vehicle.Delete:output_type -> proto.ResEmpty
	4, // 10: proto.Vehicle.GetByNoLambung:output_type -> proto.VehicleModel
	3, // 11: proto.Vehicle.GetByPool:output_type -> proto.ResVehicleList
	3, // 12: proto.Vehicle.GetAllByPrsh:output_type -> proto.ResVehicleList
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vehicle_proto_init() }
func file_vehicle_proto_init() {
	if File_vehicle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vehicle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqByNoLambung); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAllByPrsh); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqByPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResVehicleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vehicle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_proto_depIdxs,
		MessageInfos:      file_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_proto = out.File
	file_vehicle_proto_rawDesc = nil
	file_vehicle_proto_goTypes = nil
	file_vehicle_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VehicleClient is the client API for Vehicle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VehicleClient interface {
	Add(ctx context.Context, in *VehicleModel, opts ...grpc.CallOption) (*ResEmpty, error)
	Edit(ctx context.Context, in *VehicleModel, opts ...grpc.CallOption) (*ResEmpty, error)
	Delete(ctx context.Context, in *ReqByNoLambung, opts ...grpc.CallOption) (*ResEmpty, error)
	GetByNoLambung(ctx context.Context, in *ReqByNoLambung, opts ...grpc.CallOption) (*VehicleModel, error)
	GetByPool(ctx context.Context, in *ReqByPool, opts ...grpc.CallOption) (*ResVehicleList, error)
	GetAllByPrsh(ctx context.Context, in *ReqAllByPrsh, opts ...grpc.CallOption) (*ResVehicleList, error)
}

type vehicleClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleClient(cc grpc.ClientConnInterface) VehicleClient {
	return &vehicleClient{cc}
}

func (c *vehicleClient) Add(ctx context.Context, in *VehicleModel, opts ...grpc.CallOption) (*ResEmpty, error) {
	out := new(ResEmpty)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleClient) Edit(ctx context.Context, in *VehicleModel, opts ...grpc.CallOption) (*ResEmpty, error) {
	out := new(ResEmpty)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleClient) Delete(ctx context.Context, in *ReqByNoLambung, opts ...grpc.CallOption) (*ResEmpty, error) {
	out := new(ResEmpty)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleClient) GetByNoLambung(ctx context.Context, in *ReqByNoLambung, opts ...grpc.CallOption) (*VehicleModel, error) {
	out := new(VehicleModel)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/GetByNoLambung", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleClient) GetByPool(ctx context.Context, in *ReqByPool, opts ...grpc.CallOption) (*ResVehicleList, error) {
	out := new(ResVehicleList)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/GetByPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleClient) GetAllByPrsh(ctx context.Context, in *ReqAllByPrsh, opts ...grpc.CallOption) (*ResVehicleList, error) {
	out := new(ResVehicleList)
	err := c.cc.Invoke(ctx, "/proto.Vehicle/GetAllByPrsh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehicleServer is the server API for Vehicle service.
type VehicleServer interface {
	Add(context.Context, *VehicleModel) (*ResEmpty, error)
	Edit(context.Context, *VehicleModel) (*ResEmpty, error)
	Delete(context.Context, *ReqByNoLambung) (*ResEmpty, error)
	GetByNoLambung(context.Context, *ReqByNoLambung) (*VehicleModel, error)
	GetByPool(context.Context, *ReqByPool) (*ResVehicleList, error)
	GetAllByPrsh(context.Context, *ReqAllByPrsh) (*ResVehicleList, error)
}

// UnimplementedVehicleServer can be embedded to have forward compatible implementations.
type UnimplementedVehicleServer struct {
}

func (*UnimplementedVehicleServer) Add(context.Context, *VehicleModel) (*ResEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedVehicleServer) Edit(context.Context, *VehicleModel) (*ResEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (*UnimplementedVehicleServer) Delete(context.Context, *ReqByNoLambung) (*ResEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedVehicleServer) GetByNoLambung(context.Context, *ReqByNoLambung) (*VehicleModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNoLambung not implemented")
}
func (*UnimplementedVehicleServer) GetByPool(context.Context, *ReqByPool) (*ResVehicleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPool not implemented")
}
func (*UnimplementedVehicleServer) GetAllByPrsh(context.Context, *ReqAllByPrsh) (*ResVehicleList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllByPrsh not implemented")
}

func RegisterVehicleServer(s *grpc.Server, srv VehicleServer) {
	s.RegisterService(&_Vehicle_serviceDesc, srv)
}

func _Vehicle_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).Add(ctx, req.(*VehicleModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicle_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).Edit(ctx, req.(*VehicleModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicle_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqByNoLambung)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).Delete(ctx, req.(*ReqByNoLambung))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicle_GetByNoLambung_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqByNoLambung)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).GetByNoLambung(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/GetByNoLambung",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).GetByNoLambung(ctx, req.(*ReqByNoLambung))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicle_GetByPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqByPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).GetByPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/GetByPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).GetByPool(ctx, req.(*ReqByPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vehicle_GetAllByPrsh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAllByPrsh)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleServer).GetAllByPrsh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Vehicle/GetAllByPrsh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleServer).GetAllByPrsh(ctx, req.(*ReqAllByPrsh))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vehicle_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Vehicle",
	HandlerType: (*VehicleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Vehicle_Add_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _Vehicle_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Vehicle_Delete_Handler,
		},
		{
			MethodName: "GetByNoLambung",
			Handler:    _Vehicle_GetByNoLambung_Handler,
		},
		{
			MethodName: "GetByPool",
			Handler:    _Vehicle_GetByPool_Handler,
		},
		{
			MethodName: "GetAllByPrsh",
			Handler:    _Vehicle_GetAllByPrsh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vehicle.proto",
}
