package constant

const (
	//ServicePortKey ...
	ServicePortKey = "SERVICE_PORT"
	//CACertKey ...
	CACertKey = "CA_CERT"
	//ServerCertKey ...
	ServerCertKey = "SERVER_CERT"
	//KeyCertKey ...
	KeyCertKey = "KEY_CERT"
	//AppIDKey ...
	AppIDKey = "APP_ID"
	//DBHostKey ...
	DBHostKey = "DB_HOST"
	//DBNameKey ...
	DBNameKey = "DB_NAME"
	//DBUserKey ...
	DBUserKey = "DB_USER"
	//DBPasswordKey ...
	DBPasswordKey = "DB_PASSWORD"
	//DBPortKey ...
	DBPortKey = "DB_PORT"
	//DBOptionsKey ...
	DBOptionsKey = "DB_OPTIONS"
	//HTTPHeaderContentType ...
	HTTPHeaderContentType = "Content-Type"
	//ApplicationJSONUTF8Type ...
	ApplicationJSONUTF8Type = "application/json; charset=utf-8"
)
